line_length: 
- 192 # warning
- 256 # error
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
 - IzzyParserTests
disabled_rules:
 - trailing_whitespace
identifier_name:
  min_length: 2
